<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>miguelgallego-practicafinal</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="MiguelGallego-PracticaFinal_files/libs/clipboard/clipboard.min.js"></script>
<script src="MiguelGallego-PracticaFinal_files/libs/quarto-html/quarto.js"></script>
<script src="MiguelGallego-PracticaFinal_files/libs/quarto-html/popper.min.js"></script>
<script src="MiguelGallego-PracticaFinal_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="MiguelGallego-PracticaFinal_files/libs/quarto-html/anchor.min.js"></script>
<link href="MiguelGallego-PracticaFinal_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="MiguelGallego-PracticaFinal_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="MiguelGallego-PracticaFinal_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="MiguelGallego-PracticaFinal_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="MiguelGallego-PracticaFinal_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Cargar los datos en un dataframe llamado: airbnb</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>airbnb<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">'data//airbnb.csv'</span>,<span class="at">sep =</span> <span class="st">','</span>, <span class="at">stringsAsFactors =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mostrar las primeras 6 filas del dataframe</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>airbnb[<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Zipcode Neighbourhood.Cleansed Property.Type       Room.Type Accommodates
1   28004            Universidad     Apartment    Private room            2
2   28004            Universidad     Apartment Entire home/apt            6
3   28004            Universidad     Apartment Entire home/apt            3
4   28004            Universidad          Loft Entire home/apt            3
5   28015            Universidad     Apartment Entire home/apt            5
6   28004            Universidad     Apartment Entire home/apt            2
  Bathrooms Bedrooms Beds Bed.Type
1         2        1    1 Real Bed
2         1        3    5 Real Bed
3         1        2    2 Real Bed
4         2        1    1 Real Bed
5         1        1    1 Real Bed
6         1        0    1 Real Bed
                                                                                                                                                                                                                                                                                                                                                         Amenities
1                                                                                                                                                                              TV,Wireless Internet,Kitchen,Pets allowed,Pets live on this property,Buzzer/wireless intercom,Heating,Suitable for events,Washer,First aid kit,Essentials,Lock on bedroom door,Iron
2                                                                                                                                                                                      TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo
3                                                                                                                                                                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace
4                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor fireplace,Buzzer/wireless intercom,Heating,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50
5                                                                                                                                                                                                               TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Iron
6 TV,Cable TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Doorman Entry
  Square.Feet Price Review.Scores.Rating
1          NA    35                   NA
2          NA    92                   96
3          NA    55                   91
4          NA    60                  100
5         538    75                   90
6          NA    55                   95</code></pre>
</div>
</div>
<p>Renombrar las columnas de la siguiente forma:</p>
<table class="table">
<thead>
<tr class="header">
<th>Nombre original</th>
<th>Nuevo nombre</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Zipcode</td>
<td>CodigoPostal</td>
</tr>
<tr class="even">
<td>Neighbourhood.Cleansed</td>
<td>Barrio</td>
</tr>
<tr class="odd">
<td>Property.Type</td>
<td>TipoPropiedad</td>
</tr>
<tr class="even">
<td>Room.Type</td>
<td>TipoAlquiler</td>
</tr>
<tr class="odd">
<td>Accommodates</td>
<td>MaxOcupantes</td>
</tr>
<tr class="even">
<td>Bathrooms</td>
<td>NumBanyos</td>
</tr>
<tr class="odd">
<td>Bedrooms</td>
<td>NumDormitorios</td>
</tr>
<tr class="even">
<td>Beds</td>
<td>NumCamas</td>
</tr>
<tr class="odd">
<td>Bed.Type</td>
<td>TipoCama</td>
</tr>
<tr class="even">
<td>Amenities</td>
<td>Comodidades</td>
</tr>
<tr class="odd">
<td>Square.Feet</td>
<td>PiesCuadrados</td>
</tr>
<tr class="even">
<td>Price</td>
<td>Precio</td>
</tr>
<tr class="odd">
<td>Review.Scores.Rating</td>
<td>Puntuacion</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>newnames<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"CodigoPostal"</span>,<span class="st">"Barrio"</span>,<span class="st">"TipoPropiedad"</span>,<span class="st">"TipoAlquiler"</span>,<span class="st">"MaxOcupantes"</span>,<span class="st">"NumBanyos"</span>,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="st">"NumDormitorios"</span>,<span class="st">"NumCamas"</span>,<span class="st">"TipoCama"</span>,<span class="st">"Comodidades"</span>,<span class="st">"PiesCuadrados"</span>,<span class="st">"Precio"</span>,<span class="st">"Puntuacion"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(airbnb)<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"CodigoPostal"</span>,<span class="st">"Barrio"</span>,<span class="st">"TipoPropiedad"</span>,<span class="st">"TipoAlquiler"</span>,<span class="st">"MaxOcupantes"</span>,<span class="st">"NumBanyos"</span>,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="st">"NumDormitorios"</span>,<span class="st">"NumCamas"</span>,<span class="st">"TipoCama"</span>,<span class="st">"Comodidades"</span>,<span class="st">"PiesCuadrados"</span>,<span class="st">"Precio"</span>,<span class="st">"Puntuacion"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(airbnb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "CodigoPostal"   "Barrio"         "TipoPropiedad"  "TipoAlquiler"  
 [5] "MaxOcupantes"   "NumBanyos"      "NumDormitorios" "NumCamas"      
 [9] "TipoCama"       "Comodidades"    "PiesCuadrados"  "Precio"        
[13] "Puntuacion"    </code></pre>
</div>
</div>
<p>Crea una nueva columna llamada MetrosCuadrados a partir de la columna PiesCuadrados.</p>
<p>Ayuda: 1 pie cuadrado son 0,092903 metros cuadrdados</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>MetrosCuadrados <span class="ot">&lt;-</span> <span class="fu">round</span>(airbnb<span class="sc">$</span>PiesCuadrados <span class="sc">*</span> <span class="fl">0.092903</span>, <span class="dv">2</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(airbnb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   13207 obs. of  14 variables:
 $ CodigoPostal   : chr  "28004" "28004" "28004" "28004" ...
 $ Barrio         : chr  "Universidad" "Universidad" "Universidad" "Universidad" ...
 $ TipoPropiedad  : chr  "Apartment" "Apartment" "Apartment" "Loft" ...
 $ TipoAlquiler   : chr  "Private room" "Entire home/apt" "Entire home/apt" "Entire home/apt" ...
 $ MaxOcupantes   : int  2 6 3 3 5 2 7 3 2 4 ...
 $ NumBanyos      : num  2 1 1 2 1 1 5 1 1 2 ...
 $ NumDormitorios : int  1 3 2 1 1 0 1 1 1 2 ...
 $ NumCamas       : int  1 5 2 1 1 1 7 NA 1 2 ...
 $ TipoCama       : chr  "Real Bed" "Real Bed" "Real Bed" "Real Bed" ...
 $ Comodidades    : chr  "TV,Wireless Internet,Kitchen,Pets allowed,Pets live on this property,Buzzer/wireless intercom,Heating,Suitable "| __truncated__ "TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Drye"| __truncated__ "TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Sh"| __truncated__ "TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor firep"| __truncated__ ...
 $ PiesCuadrados  : int  NA NA NA NA 538 NA NA NA 700 NA ...
 $ Precio         : int  35 92 55 60 75 55 60 70 90 155 ...
 $ Puntuacion     : int  NA 96 91 100 90 95 77 84 98 NA ...
 $ MetrosCuadrados: num  NA NA NA NA 50 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airbnb<span class="sc">$</span>PiesCuadrados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  NA  NA  NA  NA 538  NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airbnb<span class="sc">$</span>MetrosCuadrados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]    NA    NA    NA    NA 49.98    NA</code></pre>
</div>
</div>
<p>Miremos el código postal. Es una variable con entradas erroneas. Hay valores como ’‘,’-’ y ‘28’ que deberían ser considerados como NA. Así mismo también debería ser NA todos los que no compiencen por 28, ya que estamos con códigos postales de Madrid</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(airbnb<span class="sc">$</span>CodigoPostal[<span class="fu">is.na</span>(airbnb<span class="sc">$</span>CodigoPostal)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(airbnb<span class="sc">$</span>CodigoPostal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> chr [1:13207] "28004" "28004" "28004" "28004" "28015" "28004" "28004" ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">startsWith</span>(airbnb<span class="sc">$</span>CodigoPostal, <span class="st">"28"</span>), <span class="cn">NA</span>, airbnb<span class="sc">$</span>CodigoPostal)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(airbnb<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">"28"</span>, <span class="cn">NA</span>, airbnb<span class="sc">$</span>CodigoPostal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>El código postal 28002, 28004 y 28051 tienen entradas repetidas. Por ejemplo las entradas 28002 deberían ir dnetro de 28002</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">grepl</span>(<span class="st">"28002"</span>, airbnb<span class="sc">$</span>CodigoPostal), <span class="st">"28002"</span>, airbnb<span class="sc">$</span>CodigoPostal)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">grepl</span>(<span class="st">"28004"</span>, airbnb<span class="sc">$</span>CodigoPostal), <span class="st">"28004"</span>, airbnb<span class="sc">$</span>CodigoPostal)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">grepl</span>(<span class="st">"28051"</span>, airbnb<span class="sc">$</span>CodigoPostal), <span class="st">"28051"</span>, airbnb<span class="sc">$</span>CodigoPostal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>El codigo 2804 debería ser 28004, 2805 deberia ser 28005 y 2815 juncto con 2815 debería ser 28015</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal[airbnb<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">"2804"</span>] <span class="ot">&lt;-</span> <span class="st">"28004"</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal[airbnb<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">"2805"</span>] <span class="ot">&lt;-</span> <span class="st">"28005"</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal[airbnb<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">"2815"</span>] <span class="ot">&lt;-</span> <span class="st">"28015"</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>CodigoPostal[airbnb<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">"280013"</span>] <span class="ot">&lt;-</span> <span class="st">"28013"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Limpia los datos de la columna Codigo Postal</p>
<p>Una vez limpios los datos ¿Cuales son los códigos postales que tenemos?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(airbnb<span class="sc">$</span>CodigoPostal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
28001 28002 28003 28004 28005 28006 28007 28008 28009 28010 28011 28012 28013 
  231   171   185  1795  1195   218   206   338   216   384   250  2060  1020 
28014 28015 28016 28017 28018 28019 28020 28021 28022 28023 28024 28025 28026 
  630   601    76   107    43   200   192    58    30    23    44   123    93 
28027 28028 28029 28030 28031 28032 28033 28034 28035 28036 28037 28038 28039 
  122   263   110    73    27    33    89    45    59    67    65    77   160 
28040 28041 28042 28043 28044 28045 28046 28047 28048 28049 28050 28051 28052 
   16    63    90   103    19   495    32    67     1     3    58    17     1 
28053 28054 28055 28056 28058 28060 28094 28105 28850 
   85    12    12     1     1     1     1     1     1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(airbnb<span class="sc">$</span>CodigoPostal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "28004" "28015" "28013" "28005" "28012" "28014" "28045" NA      "28007"
[10] "28028" "28009" "28001" "28006" "28010" "28002" "28034" "28050" "28008"
[19] "28011" "28049" "28038" "28053" "28047" "28025" "28019" "28024" "28016"
[28] "28036" "28046" "28039" "28020" "28003" "28029" "28054" "28041" "28026"
[37] "28058" "28018" "28030" "28017" "28027" "28043" "28033" "28055" "28021"
[46] "28032" "28037" "28022" "28042" "28094" "28035" "28040" "28031" "28044"
[55] "28105" "28023" "28051" "28850" "28048" "28056" "28060" "28052"</code></pre>
</div>
</div>
<p>¿Cuales son los 5 códigos postales con más entradas? ¿Y con menos? ¿Cuantas entradas tienen?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>cp_mas_entradas <span class="ot">&lt;-</span> <span class="fu">head</span>(<span class="fu">sort</span>(<span class="fu">table</span>(airbnb<span class="sc">$</span>CodigoPostal), <span class="at">decreasing =</span> <span class="cn">TRUE</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>cp_menos_entradas <span class="ot">&lt;-</span> <span class="fu">head</span>(<span class="fu">sort</span>(<span class="fu">table</span>(airbnb<span class="sc">$</span>CodigoPostal)))</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>cp_mas_entradas</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
28012 28004 28005 28013 28014 28015 
 2060  1795  1195  1020   630   601 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>cp_menos_entradas</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
28048 28052 28056 28058 28060 28094 
    1     1     1     1     1     1 </code></pre>
</div>
</div>
<p>¿Cuales son los barrios que hay en el código postal 28012?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(<span class="fu">subset</span>(airbnb, CodigoPostal <span class="sc">==</span> <span class="st">"28012"</span>)<span class="sc">$</span>Barrio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Sol"             "Acacias"         "Palos de Moguer" "Embajadores"    
 [5] "Cortes"          "Palacio"         "Universidad"     "Delicias"       
 [9] "Arapiles"        "Atocha"          "Goya"           </code></pre>
</div>
</div>
<p>¿Cuantas entradas hay en cada uno de esos barrios para el codigo postal 28012?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">subset</span>(airbnb, CodigoPostal <span class="sc">==</span> <span class="st">"28012"</span>)<span class="sc">$</span>Barrio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
        Acacias        Arapiles          Atocha          Cortes        Delicias 
             13               1               1             216               1 
    Embajadores            Goya         Palacio Palos de Moguer             Sol 
           1449               1              27              46             301 
    Universidad 
              4 </code></pre>
</div>
</div>
<p>¿Cuantos barrios hay en todo el dataset airbnb? ¿Cuales son?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(airbnb<span class="sc">$</span>Barrio))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 125</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(airbnb<span class="sc">$</span>Barrio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] "Universidad"                  "Sol"                         
  [3] "Imperial"                     "Acacias"                     
  [5] "Chopera"                      "Delicias"                    
  [7] "Palos de Moguer"              "Embajadores"                 
  [9] "Cortes"                       "Atocha"                      
 [11] "Pacífico"                     "Adelfas"                     
 [13] "Estrella"                     "Ibiza"                       
 [15] "Jerónimos"                    "Niño Jesús"                  
 [17] "Palacio"                      "Justicia"                    
 [19] "Recoletos"                    "Goya"                        
 [21] "Fuente del Berro"             "Arapiles"                    
 [23] "Trafalgar"                    "Almagro"                     
 [25] "Guindalera"                   "Lista"                       
 [27] "Castellana"                   "El Viso"                     
 [29] "Prosperidad"                  "Valverde"                    
 [31] "Casa de Campo"                "El Goloso"                   
 [33] "Numancia"                     "Cármenes"                    
 [35] "Puerta del Angel"             "Lucero"                      
 [37] "Aluche"                       "San Isidro"                  
 [39] "Campamento"                   "Comillas"                    
 [41] "Opañel"                       "Vista Alegre"                
 [43] "Ciudad Jardín"                "Hispanoamérica"              
 [45] "Nueva España"                 "Castilla"                    
 [47] "Bellas Vistas"                "Cuatro Caminos"              
 [49] "Castillejos"                  "Vallehermoso"                
 [51] "Almenara"                     "Valdeacederas"               
 [53] "Berruguete"                   "Gaztambide"                  
 [55] "Rios Rosas"                   "Peñagrande"                  
 [57] "Argüelles"                    "Puerta Bonita"               
 [59] "Buenavista"                   "Abrantes"                    
 [61] "Orcasur"                      "San Fermín"                  
 [63] "Almendrales"                  "Pradolongo"                  
 [65] "Portazgo"                     "Entrevías"                   
 [67] "San Diego"                    "Palomeras Bajas"             
 [69] "Fontarrón"                    "Vinateros"                   
 [71] "Ventas"                       "Pueblo Nuevo"                
 [73] "Quintana"                     "Concepción"                  
 [75] "San Juan Bautista"            "Costillares"                 
 [77] "Piovera"                      "Canillas"                    
 [79] "Pinar del Rey"                "Apostol Santiago"            
 [81] "San Andrés"                   "Valdefuentes"                
 [83] "Butarque"                     "Los Angeles"                 
 [85] "Casco Histórico de Vicálvaro" "Simancas"                    
 [87] "Rejas"                        "Salvador"                    
 [89] "Casco Histórico de Barajas"   "Pilar"                       
 [91] "La Paz"                       "Mirasierra"                  
 [93] "Ciudad Universitaria"         "Moscardó"                    
 [95] "Palomeras Sureste"            "Marroquina"                  
 [97] "Media Legua"                  "Los Rosales"                 
 [99] "Casco Histórico de Vallecas"  "Timón"                       
[101] "Corralejos"                   "Cuatro Vientos"              
[103] "Colina"                       "San Cristobal"               
[105] "Alameda de Osuna"             "Aeropuerto"                  
[107] "Palomas"                      "Zofío"                       
[109] "Aguilas"                      "Legazpi"                     
[111] "Fuentelareina"                "Aravaca"                     
[113] "Ambroz"                       "Canillejas"                  
[115] "Valdezarza"                   "Amposta"                     
[117] "San Pascual"                  "Santa Eugenia"               
[119] "Arcos"                        "Rosas"                       
[121] "Valdemarín"                   "El Plantío"                  
[123] "Hellín"                       "Pavones"                     
[125] "Orcasitas"                   </code></pre>
</div>
</div>
<p>¿Cuales son los 5 barrios que tienen mayor número entradas?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">sort</span>(<span class="fu">table</span>(airbnb<span class="sc">$</span>Barrio), <span class="at">decreasing =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Embajadores Universidad     Palacio         Sol    Justicia      Cortes 
       1844        1358        1083         940         785         750 </code></pre>
</div>
</div>
<p>¿Cuantos Tipos de Alquiler diferentes hay? ¿Cuales son? ¿Cuantas entradas en el dataframe hay por cada tipo?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(airbnb<span class="sc">$</span>TipoAlquiler))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(airbnb<span class="sc">$</span>TipoAlquiler)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Private room"    "Entire home/apt" "Shared room"    </code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(airbnb<span class="sc">$</span>TipoAlquiler)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Entire home/apt    Private room     Shared room 
           7903            5113             191 </code></pre>
</div>
</div>
<p>Muestra el diagrama de cajas del precio para cada uno de los diferentes Tipos de Alquiler</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> airbnb, <span class="fu">aes</span>(<span class="at">x=</span>TipoAlquiler, <span class="at">y=</span>Precio))<span class="sc">+</span><span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 9 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="MiguelGallego-PracticaFinal_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Cual es el precio medio de alquiler de cada uno, la diferencia que hay ¿es estadísticamente significativa? ¿Con que test lo comprobarías?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(Precio <span class="sc">~</span> TipoAlquiler, airbnb, mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     TipoAlquiler   Precio
1 Entire home/apt 87.29661
2    Private room 34.25514
3     Shared room 29.85340</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># str(airbnb)</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>airbnb<span class="sc">$</span>TipoAlquiler <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(airbnb<span class="sc">$</span>TipoAlquiler)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">levels</span>(airbnb<span class="sc">$</span>TipoAlquiler)){</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Tipo de alquiler:"</span>,i,<span class="st">"p-value,"</span>,</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>              <span class="fu">shapiro.test</span>(<span class="fu">sample</span>(airbnb<span class="sc">$</span>Precio[airbnb<span class="sc">$</span>TipoAlquiler<span class="sc">==</span>i], <span class="dv">5000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>))<span class="sc">$</span>p.value))</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Tipo de alquiler: Entire home/apt p-value, 1.25180288358979e-70"
[1] "Tipo de alquiler: Private room p-value, 7.5103374850614e-86"
[1] "Tipo de alquiler: Shared room p-value, 2.23714377839349e-83"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Los valores del p-valor al aplicar el test Shapiro son muy bajos, lo que nos indican que no siguen una distribución gaussiana. Por éste motivo vamos a utilizar el Kruskal test.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Utilizamos el Kruskal test y el p-valor que da de resultado es muy bajo,la prueba sugiere que hay una diferencia significativa en los precios medios entre los tres grupos de tipos de alquiler.</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>ktest <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(Precio<span class="sc">~</span>TipoAlquiler, <span class="at">data =</span> airbnb)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>ktest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  Precio by TipoAlquiler
Kruskal-Wallis chi-squared = 7235.6, df = 2, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Filtra el dataframe cuyos tipo de alquiler sea ‘Entire home/apt’ y guardalo en un dataframe llamado <em>airbnb_entire</em>. Estas serán las entradas que tienen un alquiler del piso completo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>airbnb_entire <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb, TipoAlquiler<span class="sc">==</span><span class="st">'Entire home/apt'</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(airbnb_entire)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   7903 obs. of  14 variables:
 $ CodigoPostal   : chr  "28004" "28004" "28004" "28015" ...
 $ Barrio         : chr  "Universidad" "Universidad" "Universidad" "Universidad" ...
 $ TipoPropiedad  : chr  "Apartment" "Apartment" "Loft" "Apartment" ...
 $ TipoAlquiler   : Factor w/ 3 levels "Entire home/apt",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ MaxOcupantes   : int  6 3 3 5 2 3 2 4 4 4 ...
 $ NumBanyos      : num  1 1 2 1 1 1 1 2 1 1 ...
 $ NumDormitorios : int  3 2 1 1 0 1 1 2 1 1 ...
 $ NumCamas       : int  5 2 1 1 1 NA 1 2 2 1 ...
 $ TipoCama       : chr  "Real Bed" "Real Bed" "Real Bed" "Real Bed" ...
 $ Comodidades    : chr  "TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Drye"| __truncated__ "TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Sh"| __truncated__ "TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor firep"| __truncated__ "TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/"| __truncated__ ...
 $ PiesCuadrados  : int  NA NA NA 538 NA NA 700 NA 40 646 ...
 $ Precio         : int  92 55 60 75 55 70 90 155 70 75 ...
 $ Puntuacion     : int  96 91 100 90 95 84 98 NA 90 91 ...
 $ MetrosCuadrados: num  NA NA NA 50 NA ...</code></pre>
</div>
</div>
<p>¿Cuales son los 5 barrios que tienen un mayor número de apartamentos enteros en alquiler? Nota: Mirar solo en airbnb_entire. A partir de este punto y hasta que se diga lo contrario partiremos de airbnb_entire.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>barrios_top_apartamentos <span class="ot">&lt;-</span> <span class="fu">head</span>(<span class="fu">sort</span>(<span class="fu">table</span>(airbnb_entire<span class="sc">$</span>Barrio), <span class="at">decreasing =</span> <span class="cn">TRUE</span>))</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>barrios_top_apartamentos</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Embajadores Universidad     Palacio         Sol      Cortes    Justicia 
       1228         984         769         701         574         534 </code></pre>
</div>
</div>
<p>¿Cuales son los 5 barrios que tienen un mayor precio medio de alquiler para apartamentos enteros (es decir, del dataframe airbnb_entire)?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.1     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ lubridate 1.9.2     ✔ tibble    3.2.1
✔ purrr     1.0.1     ✔ tidyr     1.3.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>barrios_top_precio <span class="ot">&lt;-</span> airbnb_entire <span class="sc">|&gt;</span> <span class="fu">group_by</span>(Barrio) <span class="sc">|&gt;</span> <span class="fu">summarize</span>(<span class="at">precio_medio =</span> <span class="fu">mean</span>(Precio)) <span class="sc">|&gt;</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(precio_medio)) <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="dv">5</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>barrios_top_precio</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  Barrio                     precio_medio
  &lt;chr&gt;                             &lt;dbl&gt;
1 Palomas                            310.
2 Fuentelareina                      180 
3 El Plantío                         150 
4 Casco Histórico de Barajas         141.
5 Alameda de Osuna                   139.</code></pre>
</div>
</div>
<p>¿Cual es su precio medio?</p>
<p>Ayuda: Usa la función aggregate <code>aggregate(.~colname,df,mean,na.rm=TRUE)</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># precio_medio_top_Barrios &lt;- mean(barrios_top_precio$precio_medio)</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="co"># precio_medio_top_Barrios</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">head</span>(<span class="fu">sort</span>(<span class="fu">aggregate</span>(Precio<span class="sc">~</span>Barrio, airbnb_entire, mean, <span class="at">na.rm=</span><span class="cn">TRUE</span>)<span class="sc">$</span>Precio, <span class="at">decreasing =</span> <span class="cn">TRUE</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 180.719</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(Precio<span class="sc">~</span>Barrio, airbnb_entire, mean, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          Barrio    Precio
1                       Abrantes  46.00000
2                        Acacias  68.16393
3                        Adelfas  68.72727
4                     Aeropuerto  38.00000
5                        Aguilas  54.50000
6               Alameda de Osuna 138.75000
7                        Almagro 109.18557
8                       Almenara  65.68000
9                    Almendrales  77.50000
10                        Aluche  55.88889
11                        Ambroz  34.50000
12              Apostol Santiago  96.60000
13                      Arapiles  69.62245
14                       Aravaca  66.33333
15                         Arcos 100.50000
16                     Argüelles  89.57343
17                        Atocha  71.44444
18                 Bellas Vistas  51.77778
19                    Berruguete  53.85714
20                    Buenavista  57.91667
21                      Butarque  42.00000
22                    Campamento  45.55556
23                      Canillas 105.80000
24                    Canillejas  91.66667
25                      Cármenes  78.00000
26                 Casa de Campo  98.85366
27    Casco Histórico de Barajas 141.25000
28   Casco Histórico de Vallecas  61.11111
29  Casco Histórico de Vicálvaro  73.87500
30                    Castellana 141.38889
31                      Castilla  68.66667
32                   Castillejos  88.70455
33                       Chopera  55.02941
34                 Ciudad Jardín  87.62500
35          Ciudad Universitaria 138.30769
36                        Colina  64.42857
37                      Comillas  56.66667
38                    Concepción  61.93750
39                        Cortes  94.39373
40                   Costillares  95.07692
41                Cuatro Caminos  76.65278
42                      Delicias  66.00000
43                    El Plantío 150.00000
44                       El Viso  76.37500
45                   Embajadores  73.70497
46                     Entrevías  56.25000
47                      Estrella  92.66667
48                     Fontarrón  51.80000
49              Fuente del Berro  70.31579
50                 Fuentelareina 180.00000
51                    Gaztambide  86.68852
52                          Goya 111.33803
53                    Guindalera  76.98780
54                        Hellín  42.00000
55                Hispanoamérica 104.44231
56                         Ibiza 102.62500
57                      Imperial  61.42857
58                     Jerónimos 131.82258
59                      Justicia  98.25468
60                        La Paz  65.33333
61                       Legazpi  79.28571
62                         Lista  90.11111
63                   Los Angeles  69.40000
64                   Los Rosales  75.00000
65                        Lucero  68.30769
66                    Marroquina  50.00000
67                   Media Legua  72.10000
68                    Mirasierra 101.28571
69                      Moscardó  56.05556
70                    Niño Jesús  89.23077
71                  Nueva España 127.30952
72                      Numancia  60.58824
73                        Opañel  51.60000
74                       Orcasur  45.00000
75                      Pacífico  89.72581
76                       Palacio  93.30599
77                       Palomas 309.75000
78               Palomeras Bajas  61.10000
79             Palomeras Sureste  31.50000
80               Palos de Moguer  73.31852
81                       Pavones  48.00000
82                    Peñagrande 127.63636
83                         Pilar  62.50000
84                 Pinar del Rey  79.88889
85                       Piovera  85.00000
86                      Portazgo  55.00000
87                    Pradolongo  61.33333
88                   Prosperidad  79.46939
89                  Pueblo Nuevo  67.46154
90                 Puerta Bonita  88.00000
91              Puerta del Angel  59.67532
92                      Quintana  65.00000
93                     Recoletos 161.92537
94                         Rejas  64.18182
95                    Rios Rosas  83.00000
96                      Salvador  66.40000
97                    San Andrés  50.91667
98                 San Cristobal  56.50000
99                     San Diego  44.34375
100                   San Fermín  63.50000
101                   San Isidro  76.10256
102            San Juan Bautista  75.53846
103                  San Pascual  72.42857
104                Santa Eugenia  47.00000
105                     Simancas  57.14286
106                          Sol 100.75036
107                        Timón  72.20000
108                    Trafalgar  98.57848
109                  Universidad  79.39674
110                Valdeacederas  67.36000
111                 Valdefuentes  84.25000
112                   Valdemarín  70.50000
113                   Valdezarza  53.33333
114                 Vallehermoso  92.39394
115                     Valverde  71.57895
116                       Ventas  50.03846
117                    Vinateros 102.50000
118                 Vista Alegre  59.45455
119                        Zofío  48.00000</code></pre>
</div>
</div>
<p>¿Cuantos apartamentos hay en cada uno de esos barrios?</p>
<p>Mostrar una dataframe con el nombre del barrio, el precio y el número de entradas.</p>
<p>Ayuda: Podeis crear un nuevo dataframe con las columnas “Barrio” y “Freq” que contenga el número de entradas en cada barrio y hacer un merge con el dataframe del punto anterior.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>airbnb_entire_freq <span class="ot">&lt;-</span> airbnb_entire <span class="sc">|&gt;</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Barrio) <span class="sc">|&gt;</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="st">`</span><span class="at">Freq</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">n</span>())</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>airbnb_barr_freq <span class="ot">&lt;-</span> <span class="fu">merge</span>(airbnb_entire_freq, <span class="fu">aggregate</span>(Precio<span class="sc">~</span>Barrio, airbnb_entire, mean, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>airbnb_barr_freq</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          Barrio Freq    Precio
1                       Abrantes    3  46.00000
2                        Acacias   61  68.16393
3                        Adelfas   33  68.72727
4                     Aeropuerto    2  38.00000
5                        Aguilas    2  54.50000
6               Alameda de Osuna    4 138.75000
7                        Almagro   97 109.18557
8                       Almenara   25  65.68000
9                    Almendrales   18  77.50000
10                        Aluche    9  55.88889
11                        Ambroz    2  34.50000
12              Apostol Santiago    5  96.60000
13                      Arapiles   98  69.62245
14                       Aravaca    9  66.33333
15                         Arcos    4 100.50000
16                     Argüelles  143  89.57343
17                        Atocha    9  71.44444
18                 Bellas Vistas   45  51.77778
19                    Berruguete   35  53.85714
20                    Buenavista   12  57.91667
21                      Butarque    1  42.00000
22                    Campamento    9  45.55556
23                      Canillas   15 105.80000
24                    Canillejas    3  91.66667
25                      Cármenes    8  78.00000
26                 Casa de Campo   41  98.85366
27    Casco Histórico de Barajas    8 141.25000
28   Casco Histórico de Vallecas   18  61.11111
29  Casco Histórico de Vicálvaro    8  73.87500
30                    Castellana   73 141.38889
31                      Castilla   21  68.66667
32                   Castillejos   44  88.70455
33                       Chopera   34  55.02941
34                 Ciudad Jardín   32  87.62500
35          Ciudad Universitaria   13 138.30769
36                        Colina    7  64.42857
37                      Comillas   21  56.66667
38                    Concepción   16  61.93750
39                        Cortes  574  94.39373
40                   Costillares   13  95.07692
41                Cuatro Caminos   72  76.65278
42                      Delicias   51  66.00000
43                    El Plantío    1 150.00000
44                       El Viso   24  76.37500
45                   Embajadores 1228  73.70497
46                     Entrevías    4  56.25000
47                      Estrella    3  92.66667
48                     Fontarrón    5  51.80000
49              Fuente del Berro   38  70.31579
50                 Fuentelareina    2 180.00000
51                    Gaztambide   61  86.68852
52                          Goya  142 111.33803
53                    Guindalera   82  76.98780
54                        Hellín    1  42.00000
55                Hispanoamérica   52 104.44231
56                         Ibiza   64 102.62500
57                      Imperial   42  61.42857
58                     Jerónimos   62 131.82258
59                      Justicia  534  98.25468
60                        La Paz    3  65.33333
61                       Legazpi   14  79.28571
62                         Lista   72  90.11111
63                   Los Angeles    5  69.40000
64                   Los Rosales    2  75.00000
65                        Lucero   13  68.30769
66                    Marroquina    2  50.00000
67                   Media Legua   10  72.10000
68                    Mirasierra    7 101.28571
69                      Moscardó   18  56.05556
70                    Niño Jesús   15  89.23077
71                  Nueva España   42 127.30952
72                      Numancia   34  60.58824
73                        Opañel   10  51.60000
74                       Orcasur    1  45.00000
75                      Pacífico   62  89.72581
76                       Palacio  769  93.30599
77                       Palomas    4 309.75000
78               Palomeras Bajas   10  61.10000
79             Palomeras Sureste    4  31.50000
80               Palos de Moguer  135  73.31852
81                       Pavones    1  48.00000
82                    Peñagrande   11 127.63636
83                         Pilar   10  62.50000
84                 Pinar del Rey    9  79.88889
85                       Piovera    3  85.00000
86                      Portazgo    1  55.00000
87                    Pradolongo    3  61.33333
88                   Prosperidad   49  79.46939
89                  Pueblo Nuevo   13  67.46154
90                 Puerta Bonita   14  88.00000
91              Puerta del Angel   77  59.67532
92                      Quintana   17  65.00000
93                     Recoletos  135 161.92537
94                         Rejas   11  64.18182
95                    Rios Rosas   60  83.00000
96                      Salvador    5  66.40000
97                    San Andrés   12  50.91667
98                 San Cristobal    2  56.50000
99                     San Diego   32  44.34375
100                   San Fermín    8  63.50000
101                   San Isidro   39  76.10256
102            San Juan Bautista   13  75.53846
103                  San Pascual    7  72.42857
104                Santa Eugenia    2  47.00000
105                     Simancas   21  57.14286
106                          Sol  701 100.75036
107                        Timón    5  72.20000
108                    Trafalgar  223  98.57848
109                  Universidad  984  79.39674
110                Valdeacederas   25  67.36000
111                 Valdefuentes   24  84.25000
112                   Valdemarín    2  70.50000
113                   Valdezarza    3  53.33333
114                 Vallehermoso   33  92.39394
115                     Valverde   19  71.57895
116                       Ventas   26  50.03846
117                    Vinateros    2 102.50000
118                 Vista Alegre   22  59.45455
119                        Zofío    4  48.00000</code></pre>
</div>
</div>
<p>Partiendo del dataframe anterior, muestra los 5 barrios con mayor precio, pero que tengan más de 100 entradas de alquiler.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>barrio_100 <span class="ot">&lt;-</span> airbnb_barr_freq <span class="sc">|&gt;</span> <span class="fu">filter</span>(Freq <span class="sc">&gt;</span> <span class="dv">100</span>) <span class="sc">|&gt;</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Precio)) <span class="sc">|&gt;</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>barrio_100</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Barrio Freq    Precio
1 Recoletos  135 161.92537
2      Goya  142 111.33803
3       Sol  701 100.75036
4 Trafalgar  223  98.57848
5  Justicia  534  98.25468</code></pre>
</div>
</div>
<p>Dibuja el diagrama de densidad de distribución de los diferentes precios. Serían 5 gráficas, una por cada barrio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>barrios <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Recoletos"</span>, <span class="st">"Goya"</span>, <span class="st">"Sol"</span>, <span class="st">"Trafalgar"</span>, <span class="st">"Justicia"</span>)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>barrios_interes <span class="ot">&lt;-</span> airbnb_entire <span class="sc">|&gt;</span> <span class="fu">filter</span>(Barrio <span class="sc">%in%</span> barrios)</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(barrios_interes, <span class="fu">aes</span>(<span class="at">x=</span>Precio, <span class="at">color=</span>Barrio)) <span class="sc">+</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Funciones de densidad por barrio"</span>, <span class="at">x=</span><span class="st">"Precio"</span>, <span class="at">y=</span><span class="st">"Densidad"</span>) <span class="sc">+</span></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 rows containing non-finite values (`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="MiguelGallego-PracticaFinal_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Calcula el tamaño medio, en metros cuadrados, para los 5 barrios anteriores y muestralo en el mismo dataframe junto con el precio y número de entradas</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>tmn_barrio_m2 <span class="ot">&lt;-</span> <span class="fu">merge</span>(barrio_100, <span class="fu">aggregate</span>(MetrosCuadrados<span class="sc">~</span>Barrio, barrios_interes, mean, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>tmn_barrio_m2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Barrio Freq    Precio MetrosCuadrados
1      Goya  142 111.33803        51.68333
2  Justicia  534  98.25468        28.52706
3 Recoletos  135 161.92537        26.66333
4       Sol  701 100.75036        45.61750
5 Trafalgar  223  98.57848        29.30429</code></pre>
</div>
</div>
<p>Dibuja el diagrama de densidad de distribución de los diferentes tamaños de apartamentos. Serían 5 gráficas, una por cada barrio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">na.omit</span>(barrios_interes), <span class="fu">aes</span>(<span class="at">x=</span>MetrosCuadrados, <span class="at">color=</span>Barrio)) <span class="sc">+</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>() <span class="sc">+</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Funciones de densidad por barrio"</span>, <span class="at">x=</span><span class="st">"Tamaño"</span>, <span class="at">y=</span><span class="st">"Densidad"</span>) <span class="sc">+</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MiguelGallego-PracticaFinal_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Esta claro que las medias de metros cuadrados de cada uno de estos 5 barrios parecen ser diferentes, pero ¿son estadísticamente diferentes? ¿Que test habría que usar para comprobarlo?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">na.omit</span>(barrios_interes), <span class="fu">aes</span>(<span class="at">x=</span>Barrio, <span class="at">y=</span>MetrosCuadrados))<span class="sc">+</span><span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MiguelGallego-PracticaFinal_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>barrios_interes<span class="sc">$</span>Barrio <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(barrios_interes<span class="sc">$</span>Barrio)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">levels</span>(barrios_interes<span class="sc">$</span>Barrio)){</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Barrio:"</span>,i,<span class="st">"p-value,"</span>,</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>              <span class="fu">shapiro.test</span>(<span class="fu">na.omit</span>(barrios_interes<span class="sc">$</span>MetrosCuadrados)[barrios_interes<span class="sc">$</span>Barrio<span class="sc">==</span>i])<span class="sc">$</span>p.value))</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Barrio: Goya p-value, 0.0496041623464228"
[1] "Barrio: Justicia p-value, 0.0153080389943869"
[1] "Barrio: Recoletos p-value, 0.00349111019694721"
[1] "Barrio: Sol p-value, 1.06967226669378e-05"
[1] "Barrio: Trafalgar p-value, 0.18769098989388"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>ktest <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(Precio<span class="sc">~</span>TipoAlquiler, <span class="at">data =</span> airbnb)</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>ktest</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  Precio by TipoAlquiler
Kruskal-Wallis chi-squared = 7235.6, df = 2, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Las medias de los los barrios (al menos uno de ellos) parecen ser estadisticamente diferentes, ya que el p-valor es miy bajo. Hemos utilizado el test kruskal porque,por lo general, la distribución de los valores no es gaussiana.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Para únicamente los pisos de alquiler en el barrio de Sol:</p>
<p><code>barrio_sol&lt;-subset(airbnb_entire,Barrio=="Sol")</code></p>
<p>Calcular un modelo lineal que combine alguna de estas variables: * NumBanyos * NumDormitorios * MaxOcupantes * MetrosCuadrados</p>
<p>Primero calculamos la correlación para ver como se relacionan estas variables entre sí.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>barrio_sol<span class="ot">&lt;-</span><span class="fu">subset</span>(airbnb_entire,Barrio<span class="sc">==</span><span class="st">"Sol"</span>)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>variables_sol <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"NumBanyos"</span>, <span class="st">"NumDormitorios"</span>, <span class="st">"MaxOcupantes"</span>, <span class="st">"MetrosCuadrados"</span>)</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>corr_variables_sol <span class="ot">&lt;-</span> <span class="fu">cor</span>(barrio_sol[variables_sol], <span class="at">use=</span><span class="st">"pairwise.complete.obs"</span>)</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>corr_variables_sol</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                NumBanyos NumDormitorios MaxOcupantes MetrosCuadrados
NumBanyos       1.0000000      0.6761906    0.6578162       0.4820403
NumDormitorios  0.6761906      1.0000000    0.7594598       0.5684425
MaxOcupantes    0.6578162      0.7594598    1.0000000       0.4286106
MetrosCuadrados 0.4820403      0.5684425    0.4286106       1.0000000</code></pre>
</div>
</div>
<p>Se observa que la correlación entre el número de dormitorios y los metros cuadrados es sorprendentemente baja. ¿Son de fiar esos números?</p>
<p>Mediante un histograma o curvas de densidad podemos descartar números que notienen sentido en el dataframe barrio_sol, para tener una matriz de correlación que tenga mayor sentido.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(barrio_sol, <span class="fu">aes</span>(<span class="at">x=</span>NumBanyos)) <span class="sc">+</span> <span class="fu">geom_density</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MiguelGallego-PracticaFinal_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(barrio_sol, <span class="fu">aes</span>(<span class="at">x=</span>NumDormitorios)) <span class="sc">+</span> <span class="fu">geom_density</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MiguelGallego-PracticaFinal_files/figure-html/unnamed-chunk-33-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(barrio_sol, <span class="fu">aes</span>(<span class="at">x=</span>MaxOcupantes)) <span class="sc">+</span> <span class="fu">geom_density</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MiguelGallego-PracticaFinal_files/figure-html/unnamed-chunk-33-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">na.omit</span>(barrio_sol), <span class="fu">aes</span>(<span class="at">x=</span>MetrosCuadrados)) <span class="sc">+</span> <span class="fu">geom_density</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MiguelGallego-PracticaFinal_files/figure-html/unnamed-chunk-33-4.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>barrio_sol <span class="ot">&lt;-</span> <span class="fu">subset</span>(barrio_sol, MetrosCuadrados <span class="sc">&gt;=</span> <span class="dv">10</span> <span class="sc">&amp;</span> MetrosCuadrados <span class="sc">&lt;=</span> <span class="dv">1000</span> <span class="sc">&amp;</span> NumDormitorios <span class="sc">&gt;=</span> <span class="dv">1</span> <span class="sc">&amp;</span> NumDormitorios <span class="sc">&lt;=</span> <span class="dv">5</span>)</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(barrio_sol<span class="sc">$</span>NumDormitorios, barrio_sol<span class="sc">$</span>MetrosCuadrados, <span class="at">col=</span><span class="st">"skyblue"</span>, <span class="at">frame.plot=</span>F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MiguelGallego-PracticaFinal_files/figure-html/unnamed-chunk-33-5.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(barrio_sol[variables_sol], <span class="at">use=</span><span class="st">"pairwise.complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                NumBanyos NumDormitorios MaxOcupantes MetrosCuadrados
NumBanyos       1.0000000      0.7337699    0.8579905       0.5928683
NumDormitorios  0.7337699      1.0000000    0.7827712       0.8163709
MaxOcupantes    0.8579905      0.7827712    1.0000000       0.6957486
MetrosCuadrados 0.5928683      0.8163709    0.6957486       1.0000000</code></pre>
</div>
</div>
<p>Una vez que hayamos filtrado los datos correspondientes calcular el valor o la combinación de valores que mejor nos permite obtener el precio de un inmueble.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">repr.plot.height=</span><span class="dv">4</span>,<span class="at">repr.plot.width=</span><span class="dv">6</span>)</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(<span class="fu">na.omit</span>(barrio_sol[,<span class="fu">c</span>(<span class="st">"NumBanyos"</span>, <span class="st">"NumDormitorios"</span>, <span class="st">"MaxOcupantes"</span>, <span class="st">"MetrosCuadrados"</span>, <span class="st">"Precio"</span>)]),</span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>       <span class="co">#lower = list(continuous = wrap("density", alpha = 0.8,size=0.2,color='blue'))</span></span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">lower =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="fu">wrap</span>(<span class="st">"points"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>,<span class="at">size=</span><span class="fl">0.1</span>,<span class="at">color=</span><span class="st">'blue'</span>))</span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>       )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="MiguelGallego-PracticaFinal_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>¿Que variable es más fiable para conocer el precio de un inmueble, el número de habitaciones o los metros cuadrados?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>model<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>barrio_sol, <span class="at">formula =</span> Precio <span class="sc">~</span> NumBanyos<span class="sc">+</span>NumDormitorios<span class="sc">+</span>MaxOcupantes<span class="sc">+</span>MetrosCuadrados)</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Precio ~ NumBanyos + NumDormitorios + MaxOcupantes + 
    MetrosCuadrados, data = barrio_sol)

Residuals:
    Min      1Q  Median      3Q     Max 
-85.043 -13.253  -2.146  19.666  60.824 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)      24.0965    13.8768   1.736  0.09432 . 
NumBanyos        -2.3021    15.6013  -0.148  0.88383   
NumDormitorios   32.5224    10.1109   3.217  0.00346 **
MaxOcupantes      2.7080     4.7448   0.571  0.57308   
MetrosCuadrados   0.1999     0.2200   0.909  0.37195   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 32.59 on 26 degrees of freedom
Multiple R-squared:  0.7534,    Adjusted R-squared:  0.7155 
F-statistic: 19.86 on 4 and 26 DF,  p-value: 1.346e-07</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># La variable más representativa para conocer el precio del inmuble es sin duda el numero de habitaciones.</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>model<span class="ot">&lt;-</span><span class="fu">lm</span>(<span class="at">data=</span>barrio_sol, <span class="at">formula =</span> Precio <span class="sc">~</span> NumDormitorios)</span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %   97.5 %
(Intercept)    11.41223 54.36366
NumDormitorios 33.01073 52.28146</code></pre>
</div>
</div>
<p>Responde con su correspondiente margen de error del 95%, ¿cuantos euros incrementa el precio del alquiler por cada metro cuadrado extra del piso?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># El precio del alquiler aumenta 1.28€ por cada metro cuadrados extra de la vivienda.</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(<span class="fu">lm</span>(<span class="at">data=</span>barrio_sol, <span class="at">formula =</span> Precio <span class="sc">~</span> MetrosCuadrados))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    2.5 %    97.5 %
(Intercept)     3.6988423 62.960479
MetrosCuadrados 0.6543305  1.280113</code></pre>
</div>
</div>
<p>Responde con su correspondiente margen de error del 95%, ¿cuantos euros incrementa el precio del alquiler por cada habitación?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co"># El precio del alquiler aumenta 52.28€ por cada habitación extra de la vivienda.</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(<span class="fu">lm</span>(<span class="at">data=</span>barrio_sol, <span class="at">formula =</span> Precio <span class="sc">~</span> NumDormitorios))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %   97.5 %
(Intercept)    11.41223 54.36366
NumDormitorios 33.01073 52.28146</code></pre>
</div>
</div>
<p>¿Cual es la probabilidad de encontrar, en el barrio de Sol, un apartamento en alquiler con 3 dormitorios?</p>
<p>¿Cual es el intervalo de confianza de esa probabilidad?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co"># La probabilidad de encontrar una vivienda en sol con 3 dormitorios es del 9.68%. El intervalo de confianza está entre el 2.04% y el 25.75%.  El intervalo de confianza es alto.</span></span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>n_apartamentos_3dormitorios <span class="ot">&lt;-</span> <span class="fu">sum</span>(barrio_sol<span class="sc">$</span>NumDormitorios <span class="sc">==</span> <span class="dv">3</span>)</span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(n_apartamentos_3dormitorios, <span class="fu">length</span>(barrio_sol<span class="sc">$</span>NumDormitorios), <span class="at">p =</span> <span class="fl">0.5</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  n_apartamentos_3dormitorios and length(barrio_sol$NumDormitorios)
number of successes = 3, number of trials = 31, p-value = 4.649e-06
alternative hypothesis: true probability of success is not equal to 0.5
95 percent confidence interval:
 0.02041986 0.25753906
sample estimates:
probability of success 
            0.09677419 </code></pre>
</div>
</div>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>